In [2]:
import numpy as np

tab1 = np.array([[1,2], [3,4], [5,6]])
print(tab1)
# Crée un tableau de 3 lignes et 2 colonnes
tab2 = np.array([[1,2,3], [4,5,6]])
print(tab2)
# Crée un tableau de 2 lignes et 3 colonnes

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [4]:
test = np.ones((3,5))
print(test)
# Crée un tableau de 3x5 rempli de 1

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
test2 = np.random.random((6,3))
print(test2)
# Créé un tableau de 6 x 3 avec des valeurs aléatoires

[[0.10608824 0.27874296 0.69721918]
 [0.48838345 0.46783534 0.40901168]
 [0.0098777  0.43006299 0.14948594]
 [0.6616788  0.02865061 0.44731148]
 [0.17893711 0.53683043 0.37761192]
 [0.36859558 0.81018939 0.4678211 ]]


In [8]:
test3 = np.random.randint(1,10, size=(3,3))
print(test3)
# Crée un tableau de 3x3 avec des valeurs aléatoires entières comprises entre 1 et 10

[[6 8 3]
 [2 4 9]
 [3 3 6]]


In [11]:
# Les arrays Numpy peuvent être utilisés comme des matrices 
A = np.array([[1,2], [3,4]])
B = np.array([[5,10], [15,20]])
test = A + B 
print(test)

[[ 6 12]
 [18 24]]


In [13]:
test2 = A * B
print(test2)

[[ 5 20]
 [45 80]]
