In [10]:
revenus = [1800, 1500, 2200, 3000, 2172]

In [9]:
def moyenne(list) :
    return sum(list)/len(list)

moyenne(revenus)

2134.4

In [14]:
import numpy as np 
np.mean(revenus)
# Permet de faire le même calcul que la fonction moyenne. 

2134.4

In [16]:
import numpy as np
x = [-2, -1, 1, 2]
print("La valeur absolue : ", np.abs(x)) 
print("Exponentielle : ", np.exp(x))
print("Logarithme : ", np.log(np.abs(x)))

La valeur absolue :  [2 1 1 2]
Exponentielle :  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme :  [0.69314718 0.         0.         0.69314718]


In [17]:
revenus_array = np.array(revenus)
print(revenus_array)

[1800 1500 2200 3000 2172]


In [23]:
test_zero = np.zeros(4)
print("test_zero : ", test_zero)
print(test_zero.dtype)
# numpy.dtype permet d'indiquer le type de valeurs présentes dans le tableau (array) Numpy. 
# Dtype retourne deux choses : - le type (int, float, ...) & - la précision (ici 64) 
test_one = np.ones(4)
print("test_one : ", test_one)
print(test_one.dtype)
test_nparange = np.arange(1, 5, 1)
print("test nparange : ", test_nparange)
print(test_nparange.dtype)
test_linspace = np.linspace(1,5,5)
print("test linspace : ", test_linspace)
print(test_linspace.dtype)

test_zero :  [0. 0. 0. 0.]
float64
test_one :  [1. 1. 1. 1.]
float64
test nparange :  [1 2 3 4]
int64
test linspace :  [1. 2. 3. 4. 5.]
float64


In [34]:
# Séléctionner des éléments au sein d'un array 
print(revenus_array[0])
print(revenus_array[1])
# Retourne les entrées séléctionnées
print(revenus_array[0:3:1])
print(revenus_array[0:5:1])
# liste[indice de départ : indice de fin : step ]
print(revenus_array[0:2])
# Dans cette notation, l'indice de fin est exclu, on a que les éléments d'indice 0 et 1. 
print(revenus_array[:3])
# On affiche les trois premiers éléments, l'indice de début peut être exclu. 
print(revenus_array[2:])
# On affiche les éléments à partir de l'indice 2 inclus
print(revenus_array[::2])
# On affiche un  élément sur 2
print(revenus_array[::-1])
# On peut faire ça pour inverser l'ordre d'un tableau 

1800
1500
[1800 1500 2200]
[1800 1500 2200 3000 2172]
[1800 1500]
[1800 1500 2200]
[2200 3000 2172]
[1800 2200 2172]
[2172 3000 2200 1500 1800]


In [37]:
# On peut aller plus loin dans la séléction
print(revenus_array[revenus_array > 2000])
# On peut compléxifier la séléction 
print(revenus_array[(revenus_array > 2000) & (revenus_array < 3000)])

[2200 3000 2172]
[2200 2172]


In [57]:
# AUTRES METHODES d'array
print(revenus_array.dtype)
# Retourne le type de valeurs contenues dans le tableau
print(revenus_array.shape)
# Explique que l'on a un array contenant 5 éléments, le point après la virgule sera défini ultérieurement
print(revenus_array.mean())
# Retourne la moyenne des valeurs du tableau 
print(revenus_array.max())
print(revenus_array.min())
# Retourne la valeur max ou mini des valeurs du tableau 
print(revenus_array.argmin())
print(revenus_array.argmax())
# Retourne l'indice de la valeur maximale ou minimale du tableau 
revenus_array.sort()
print(revenus_array)
# Trier le tableau 
# Ici c'est broken parce que je l'ai exécuté dans un print, mais ça marche 
print(revenus_array.sum())
# Calculer la somme des valeurs du tableau 



int64
(5,)
2134.4
3000
1500
0
4
[1500 1800 2172 2200 3000]
10672
