In [1]:
import numpy as np

In [3]:
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
a = np.linspace(5,10,11)
print(a[-3:-1])

[9.  9.5]


In [9]:
print(a)
print(a[a % 2 == 0])

[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ]
[ 6.  8. 10.]


In [13]:
b = np.array([[[1,2],[4,5]], 
              [[6,7],[8,9]], 
              [[10,11],[12,13]]])
print(b)

[[[ 1  2]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]


In [16]:
b.reshape([4,1,3])

array([[[ 1,  2,  4]],

       [[ 5,  6,  7]],

       [[ 8,  9, 10]],

       [[11, 12, 13]]])

In [18]:
print(b[2,:,:])

[[10 11]
 [12 13]]


In [20]:
print(b[b>10])

[11 12 13]


In [21]:
print(b[2,:,2])

IndexError: index 2 is out of bounds for axis 2 with size 2